name: Portable

on: 
   push:
     branches : 
       - portable
   pull_request:
     branches : 
       - portable

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - name: install chez scheme
      run: brew install chezscheme
    - name: install gambit scheme
      run: |
           brew install gambit-scheme
           sudo ln -s /usr/local/Cellar/gambit-scheme/4.9.3_1/gsi /usr/local/gsi
    - name : prepare files
      run: |
            git clone -b portable https://github.com/guenchi/json
            cd json
            mkdir json
            mv json.sc json/json.ss
    - name: test with chez scheme
      run:  |
            cd json
            chez test/test.sc
    - name: test with gambit scheme
      run:  |
            cd json
            gsi test/test.sc

  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: install chez scheme
      run: sudo apt install chezscheme
    - name : test
      run: |
            git clone -b portable https://github.com/guenchi/json
            cd json
            mkdir json
            mv json.sc json/json.ss
            scheme test/test.sc
