name: Portable

on: 
   push:
     branches : 
       - portable
   pull_request:
     branches : 
       - portable

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: install chez scheme
      run: brew install chezscheme
    - name : test
      run: |
            git clone -b portable https://github.com/guenchi/json
            cd ./json
            mkdir json
            mv ./json.sc ./json/json.ss
            chez ./test/test.sc
