name: MacOS

on: 
   push:
     branches : 
       - portable
   pull_request:
     branches : 
       - portable

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: install chez scheme
      run: |
           brew install chezscheme
           cd /usr/local/bin
           cp chez scheme
    - name: install raven
      run: curl -L http://ravensc.com/install | scheme
    - name : test
      run: |
            git clone https://github.com/guenchi/json@portable
            cd ./json
            mkdir lib
            cd ./lib
            mkdir json
            cd ../
            mv ./json.sc ./lib/json/
            raven run ./test/test.sc
